### ISSUE TITLE
Method to Convey Multiple SSRCs for a given stream

### ISSUE THREAD

**Issue by kyzer-davis** [kyzer-davis/srtp-assurance-rfc-draft#1]
Need to provide context when multiple SSRCs are being multiplexed. 
Current text states to use EKT-SRTP for this but could be a solution available:

### Solution A:
Multiple `a=srtpctx` lines each with a given identifier where the first number corresponds with the a=crypto tag and the second number corresponds with the multiplxed SSRC identifier
```
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSo
a=srtpctx:1:1 ssrc=0x01;roc=0x0;seq=0x1234
a=srtpctx:1:2 ssrc=0x02;roc=0x1;seq=0xABCD
a=srtpctx:1:3 ssrc=0x845fed;roc=0x0000;seq=unknown
```

### Solution B:
Cram everything into one `a=srtpctx` line as a list and wrap each multiplexed item in parenthesis.
```
a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSo
a=srtpctx:1 (ssrc=0x01;roc=0x0;seq=0x1234), (ssrc=0x02;roc=0x1;seq=0xABCD), (ssrc=0x845fed;roc=0x0000;seq=unknown)
```

**Comment by valvo27** [comment]
Solution A is cleaner and easier to read for humans.
