### ISSUE TITLE
Discuss sending some update when ROC updates

### ISSUE THREAD

**Issue by kyzer-davis** [kyzer-davis/srtp-assurance-rfc-draft#10]
Is it required?
e.g When the ROC updates should I send some SDP via SIP UPDATE/REINVITE to signal such? 

Current text just discusses sending it at natural times when we are sending a=crypto. Thus normal offer/answer, updates, or session refreshes which would catch 99.9% of scenarios.

Would go in "3.4.  Update Frequency" section

**Comment by valvo27** [comment]
While the session is active all parties are aware of the ROC value. I don't see the need to update everyone at ROC change and more so at renegotiation of session change to sync all parties involved in the media exchange or like you said session refreshes, etc that are natural signaling exchanges that take place.
