### ISSUE TITLE
Discuss why this can't be a RTP Header Extension

### ISSUE THREAD

**Issue by kyzer-davis** [kyzer-davis/srtp-assurance-rfc-draft#11]
Some text, maybe in appendix.

the short; if we want compatibility with `a=cryptex` there is a chicken or egg scenario where the RTP header extensions would be encrypted rendering the conveyed SRTP context information to decrypt the packet data useless.

**Comment by valvo27** [comment]
extmaps are a thing now within the SDP that could add RTP Header Extensions. They are used in Webex App, but not widely used yet. I rather go the SDP route that we are currently in.
